matrix:
  include:
    - language: node_js
      node_js: '12'
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
        - yarn add coveralls
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - language: python
      python: 3.7
      addons:
        sonarcloud:
          organization: "swsnu"
          token:  
            secure: "zhUuxklnXXMZ+5oX+AHSN9o2dwyNHjAeyuqd3QrEsaaDU3M/fPCBnXOsJVt+XQsxfMMy8u593LdUR01xNSAtlFrNrmGC2H/vc3Azjh9OeCPSb+P1tGRZOCLNgpnaWttf4dtd3SD4/roBLLZRxKHViORf+R6oIYELQk5/7QBDzcVa21Zs8coXX06/Ql+c4pDM61Vgj1lkUgSpKKtUtkZAca3gOT8Ucp3LVmJBhRUH96kdJqcHEZ5pg5ddcO42vL0AdT02MSY2Bubk+hrAJcRhHKTWNvz/XtjTqZwY2z6r5owyh37FKo+5ARSjmVszijG2ofIQEVAlAA39iu1Ow86wNHu/Walcn1YBc5y/jNjXCLXci6YokYhs3kueWZ8GyaLG30pBRpBcZ24d5NUrej12Vqvlhyz1+b8W1lhRyHUPPhtXMs3jOvV/gdJhGFlrUf8emJNRupfUDHSOfKOarsTf31rG8DzrfdWe0KlHYhiie13bKQryAlac339XmcBcYFOCvctM45xYMxfAFzg74Tvxztja+yyrdqq1OcDuJY4ORaj1ESASKtyGKISdbfmFGAhd89XdegonEUcM5I1YWOnHfGRKPnQx090yEfYsr9n4SaRuQ0QvBo9QyOMWYhG6lDSTePf2Nk5ecz+N6SkG1zYYcNMCqEsuV0FC2kGiPgHOWXs="
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ..
        - sonar-scanner
      after_success:
        - coveralls
