matrix:
  include:
    - addons:
        sonarcloud:
          organization: swsnu
          token:
            secure: "ZzZrEBnCja4aJjGZsLOnZCOxaxBA7Vl0O5A1vDX58xZ0H8Kn5sWp8GjmPi+k1nTx+DFq/hW/7fpWnN2hj7JZumRvgzREP1HW+WyRxH4GAKpex/pJNMOkrF92d486fo35E9wwZv5bukpXX43Sk5DzzefE+mWntjAphBEyEda39NcSWMCfmpDrvWHausNm8rzt0hqhBi2hH8lDtSFqey57k/Zo9V5ZwZaz2wHkMjeiMndtED0i4e/hvRfQtHtt7b+EjSCfWYzlvdE2l8FL5U08A5eyvrrXc32PDCVcl241Ck8pZ8AgOrJ4lnehxLThBlxYQDw2bEgUmKHjb9VFNJf8G2qIfQg2qQkwwuG/Jc7s99sX8NKVhdEZz5bBvZgtiiprX0UvcGIFZLEVtO7NaQYfBAwBiMgMbeQbSae2ppMBxSLvFMf0bubWDCMKZE9j/iE/ZFWT50eg1NY5yczXLzTDw3BVnNQ1Q/BFrBvBFC1dBMrEx1m0HEof8p6nYFcpjALiHenXEACB/nfj2ZQugHggtlimWQS6Dqz0zMv+K90asvUofY/nGHDMAoMW4feFu9nzntEQogQPKBGpl2s5cBhGMVwzVmmwN0NnZF7lc3QqXnfRc4qg59RiqykFBQbxj0atEIQL2zum+XFAGMa3sCkKTLBiFlRnlpFGbf6MBY+h3lc="
      node_js: '12'
      language: node_js
      python: 3.7
      dist: bionic
      cache:
        - yarn: true
        - pip: true
      before_install:
      install:
        - cd frontend
        - yarn install
        - yarn add coveralls
        - cd ..
        - pip install virtualenv
        - virtualenv --python=python3.7 venv
        - source venv/bin/activate
        - pip install django
        - cd backend
        - python manage.py makemigrations ATM
        - python manage.py migrate
        - cd ..
      script:
        - cd frontend
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd .. && sonar-scanner
      after_success:
        - cat ./frontend/coverage/lcov.info | ./frontend/node_modules/coveralls/bin/coveralls.js

