export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const GET_USER = 'GET_USER';
export const EDIT_USER = 'EDIT_USER';
export const CHANGE_PREFERENCE_VECTOR = 'CHANGE_PREFERENCE_VECTOR';
export const GET_RESTAURANT_REVIEWS = 'GET_RESTAURANT_REVIEWS';
