export const GET_RESTAURANTLIST = 'GET_RESTAURANTLIST';
export const GET_RESTAURANTNAME = 'GET_RESTAURANTNAME';
export const GET_RESTAUARANTDETAIL='GET_RESTAURANTDETAIL';
export const CHANGE_LOCATION    = 'CHANGE_LOCATION';
export const GET_USER = 'GET_USER';
export const EDIT_USER = 'EDIT_USER';