# Generated by Django 3.1.3 on 2020-12-03 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('한식', models.BooleanField(default=False)),
                ('일식', models.BooleanField(default=False)),
                ('중식', models.BooleanField(default=False)),
                ('양식', models.BooleanField(default=False)),
                ('카페', models.BooleanField(default=False)),
                ('기타', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('address_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('매운', models.FloatField(default=0.0)),
                ('느끼한', models.FloatField(default=0.0)),
                ('짭짤한', models.FloatField(default=0.0)),
                ('달달한', models.FloatField(default=0.0)),
                ('고소한', models.FloatField(default=0.0)),
                ('싱거운', models.FloatField(default=0.0)),
                ('담백한', models.FloatField(default=0.0)),
                ('바삭바삭한', models.FloatField(default=0.0)),
                ('부드러운', models.FloatField(default=0.0)),
                ('저렴한', models.FloatField(default=0.0)),
                ('웨이팅이있는', models.FloatField(default=0.0)),
                ('혼밥하기좋은', models.FloatField(default=0.0)),
                ('불친절한', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='ATM.foodcategory')),
                ('preference_vector', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='ATM.preferencevector')),
                ('search_location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='ATM.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avg_rating', models.FloatField()),
                ('food_category', models.CharField(max_length=100)),
                ('menu', models.JSONField()),
                ('openTime', models.JSONField()),
                ('thumbnail', models.JSONField()),
                ('keyword', models.JSONField(null=True)),
                ('kakao_link', models.URLField()),
                ('naver_link', models.URLField()),
                ('map_link', models.URLField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ATM.location')),
                ('preference_vector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ATM.preferencevector')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_site_author', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
                ('date', models.DateTimeField()),
                ('site', models.CharField(max_length=10)),
                ('atm_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ATM.profile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ATM.restaurant')),
            ],
        ),
    ]
