# Generated by Django 3.1.2 on 2020-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='기타',
            new_name='간식',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='분식',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='술집',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='아시아음식',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='치킨',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='패스트푸드',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='퓨전요리',
            field=models.BooleanField(default=False),
        ),
    ]
