# Generated by Django 3.1.3 on 2020-12-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='radius',
            field=models.FloatField(default=10),
        ),
    ]
