# Generated by Django 3.1.3 on 2020-11-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='source',
            new_name='sourceSite',
        ),
    ]
