# Generated by Django 3.1.3 on 2020-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_profile_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='radius',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_tab',
            field=models.CharField(default='MyInfo', max_length=20),
        ),
    ]
