# Generated by Django 3.1.3 on 2020-11-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_auto_20201118_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sourceSite',
            new_name='site',
        ),
    ]
