# Generated by Django 3.1.3 on 2020-12-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0003_auto_20201213_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='radius',
            field=models.FloatField(default=10),
        ),
    ]
