# Generated by Django 3.1.3 on 2020-12-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_remove_preferencevector_싱거운'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencevector',
            name='담백한',
        ),
    ]
